### ISSUE TITLE
check package

### ISSUE THREAD

**Issue by Dschaykib** [STATWORX/helfRlein#1]
## Tasks
- [x] check dependencies
- [x] check format of functions ( "_" not "." in names)
- [x] check manual pdf
- [x] check usage of package
